services:
  # E-Learning Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: elearning-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
    networks:
      - elearning-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      timeout: 5s
      retries: 3
      start_period: 30s
      interval: 30s

  # Nginx Reverse Proxy (Optional - bisa langsung expose app juga)
  nginx:
    image: nginx:alpine
    container_name: elearning-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    networks:
      - elearning-network
    profiles:
      - production

networks:
  elearning-network:
    driver: bridge
